version: '3'

services:
  db:
    image: mongo
    container_name: db
    hostname: database
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python3 manage.py runserver 0:8000
    container_name: web
    #entrypoint: tail -f
    #command: /dev/null
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DB_HOST : "mongodb://database/Tutorial"
      DJANGO_SETTINGS_MODULE: "DRFtutorial.settings"
    links:
      - 'db'
