# Generated by Django 4.1.9 on 2023-05-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='skills',
        ),
        migrations.AddField(
            model_name='teacher',
            name='skills',
            field=models.ManyToManyField(to='tutorials.skill'),
        ),
    ]
